import {
  PenTool,
  Smartphone,
  Workflow,
  Megaphone,
  LifeBuoy,
  Palette,
  Search,
  Compass,
  LayoutGrid,
  Ruler,
  Accessibility,
  Code2,
  Server,
  Cloud,
  GitBranch,
  Plug,
  BarChart3,
  Target,
  Mail,
  Share2,
  Calendar,
  ShieldCheck,
  Activity,
  Zap,
  RefreshCw,
  Lock,
  Sparkles,
  Users,
  Globe,
  Lightbulb,
  Heart,
  Award,
  Rocket,
  Handshake,
  Scale,
  Leaf,
  Eye,
  MessageCircle,
  TrendingUp,
  Layers,
  Database,
  Cpu,
  Monitor,
  Gauge,
  BrainCircuit,
  Bot,
  Building2,
  ScanText,
  LineChart,
  Cog,
  Headset,
  Wand2,
  Network,
  type LucideIcon,
} from "lucide-react";

export const iconMap = {
  penTool: PenTool,
  smartphone: Smartphone,
  workflow: Workflow,
  megaphone: Megaphone,
  lifeBuoy: LifeBuoy,
  palette: Palette,
  search: Search,
  compass: Compass,
  layoutGrid: LayoutGrid,
  ruler: Ruler,
  accessibility: Accessibility,
  code: Code2,
  server: Server,
  cloud: Cloud,
  gitBranch: GitBranch,
  plug: Plug,
  barChart: BarChart3,
  target: Target,
  mail: Mail,
  share: Share2,
  calendar: Calendar,
  shield: ShieldCheck,
  activity: Activity,
  zap: Zap,
  refresh: RefreshCw,
  lock: Lock,
  sparkles: Sparkles,
  users: Users,
  globe: Globe,
  lightbulb: Lightbulb,
  heart: Heart,
  award: Award,
  rocket: Rocket,
  handshake: Handshake,
  scale: Scale,
  leaf: Leaf,
  eye: Eye,
  message: MessageCircle,
  trendingUp: TrendingUp,
  layers: Layers,
  database: Database,
  cpu: Cpu,
  monitor: Monitor,
  gauge: Gauge,
  brainCircuit: BrainCircuit,
  bot: Bot,
  building: Building2,
  scanText: ScanText,
  lineChart: LineChart,
  cog: Cog,
  headset: Headset,
  wand: Wand2,
  network: Network,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;
